language: minimal
os: linux
dist: bionic

env:
  global:
    - IMAGE_NAME=jsloan117/sabnzbd

notifications:
  email: false

jobs:
  include:
    - stage: build docker images
      services: docker
      script: .travis/build-test-push.sh
      cache:
        directories:
          - $HOME/.cache/trivy

    - stage: build documentation
      if: branch = dev
      language: python
      python: 3.7.5
      cache: pip
      script: .travis/build-and-deploy-docs.sh
